"""Utility to generate an .env file with offline defaults."""
from __future__ import annotations

import argparse
from pathlib import Path

from svt_core.config.defaults import DEFAULT_ENV, DefaultPaths


def ensure_directories(paths: DefaultPaths) -> None:
    for path in (paths.input_dir, paths.output_dir, paths.memory_dir):
        path.mkdir(parents=True, exist_ok=True)


def write_env_file(target: Path, overwrite: bool = False) -> None:
    if target.exists() and not overwrite:
        print(f"⚠️ {target} exists. Use --overwrite to regenerate.")
        return

    lines = ["# Generated by svt_core.tools.generate_env", ""]
    for key, value in DEFAULT_ENV.items():
        lines.append(f"{key}={value}")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ Wrote {target}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate .env with offline defaults")
    parser.add_argument("--path", default=".env", help="Target .env path")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing file")
    args = parser.parse_args()

    ensure_directories(DefaultPaths())
    write_env_file(Path(args.path), overwrite=args.overwrite)


if __name__ == "__main__":
    main()
